# Generated by Django 4.0.4 on 2022-06-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
                ('cuit', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distribuidores_Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.IntegerField()),
                ('distribuidor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('marca', models.CharField(max_length=3)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.IntegerField()),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('descuento', models.FloatField()),
                ('novedad', models.BooleanField()),
                ('imagen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
